### ISSUE TITLE
Không nên áp dụng công nghiệp hóa như kiểu này vào thực tế :))

### ISSUE THREAD

**Issue by tunnaduong** [thaiminhpv/hr-facebook-cf-checker#1]
như tiêu đề. hahaa. tôi nghĩ vậy

**Comment by thaiminhpv** [comment]
If you notice the last active commit was actually 2 years ago :)) I made this project as a personal tool for myself at the time when I was 'young' :))

**Comment by tunnaduong** [comment]
lmao =))) ơ nma nói thật. kể ra bây giờ ông còn xài lại cái tool đấy cho JS thì tôi cũng phải hiểu ông chỉ biết code th mà k nghĩ đến vấn đề thực tế ấy =))). để phân tích cho:

### VẤN ĐỀ CỦA BÀI TOÁN THỰC TẾ RÚT RA TỪ CHÍNH BẢN THÂN
- Thứ nhất, mấy ông có thể áng chừng cũng đc mà, cứ xem tất cả bài viết. Xem quanh đi quẩnh lại trước giờ có bao nhiêu đứa là hay cf. Còn lại là xem chùa hoặc bận k đến đc hoặc bận k thèm like cmt cf nhưng vẫn đến, cả thành viên đang deactive hoặc chuẩn bị kick. Còn một số thành phần kiểu còn đang mông lung trong cái time table của hôm đó cơ. Đ biết nên cf hay k ý. Cf đi đc thì k sao. Cf xong đ đi thì bị chửi 🙂 Chửi xong hsau sợ quá đjt cf nữa :))) hiểu vấn đề ko.
- Mà tính tôi kiểu trước giờ đ bao giờ vào cf từ hồi ctv đến lúc thành viên chính thức, t không cf một bài viết nào kiểu đi ăn căn tin hay cf kick off hay challenge các thứ. nma vẫn dành sự quan tâm, một số hôm vẫn đi. Trừ một số lý do mà một số hôm k đi đc với ae hoặc kiểu ngại va chạm do mới vào th.
- Cái gạch đầu dòng đầu tiên ý, sau khi có được, cái data này có thể dùng để tạo ra biểu đồ cũng đc. Cái cần nhất bây giờ k phải file sheet xem anh em check cf đc bn lần. Mà cái các anh chị ban đầu não cần là cái biểu đồ dạng analytics tổng quan chất lượng thành viên nhóm trong clb để còn chỉ ra điểm yếu và điểm mạnh, thời điểm và event nào anh em tham gia đông đủ nhất và cái nào là nhạt và ít người chú ý. (cái này nếu làm được phát triển mạnh ra thành kiểu xem analytics theo khoảng thời gian kiểu, tháng, tuần, năm,... nếu ông bạn định thử sức làm những điều mới lạ vượt ra khỏi khả năng của bản thân =))) Quan trọng nhất là cách để lấy dữ liệu trong trường hợp làm nhóm kín clb không phải là tạo con bot check cf auto hay script gì chèn vào inject, crawl đâu. Mịe nó thời gian ông code tôi review được performance của tất cả các thành viên trong clb dựa qua việc tự tổng hợp bằng tay thủ công lướt tất cả post chỉ ra thằng nào hay cf bài cũ, và bài mới đ cf nữa, kết hợp thêm với dựa trên việc quan sát bằng mắt, bằng đầu (đ phải AI Camera =))) của mấy ông quản trị là biết được ngay bố nào kì tới inactive chuẩn bị kick mẹ ra khỏi clb cmnr =))). Điều quan trọng phải nhắc lại lần 2 ở đây là làm THỦ cmn CÔNG ý và tự tổng hợp lại. Mà ở đây tôi thấy mấy web app kiểu excel sheet thừa sức làm được, chỉ cần data và tí kinh nghiệm là xong mẹ nó cả ý tưởng của tôi (là làm dạng analytics. nếu ông rảnh thì làm thành bản web cũng đc)

### => Chốt lại:
- Không thực tế
- Không nói lên được điều gì qua kết quả
- Tốn thời gian, sức lực, tuổi xuân, thời gian anh em gen 10 BCM CLB đi nhậu =))
- Chính ra tôi thấy ông làm giải pháp này mà chính ông còn không thấy có mặt bao giờ =))))
- Cách thủ công vẫn tốt hơn, nhanh hơn
- Cần thử sức với những thứ khó hơn nếu muốn gây ấn tượng cho ban chủ nhiệm (cái này tôi crawl làm trong 1 buổi là xong để showcase techtalk API =)) nếu còn nhớ và có xem. ở đây khó hơn là kiểu cái biểu đồ rồi xem theo khoảng thời gian các thứ)
- Nếu ông đã quá chán với việc code mấy cái web tool thì ông có thể thử code sang tí mobile app rồi làm tí AI cho cái tôi bảo analytics giúp CLB phân tích tự động tính điểm performance từng thành viên qua việc training data deep learning dữ liệu các thành viên gen cũ ngày xưa và tỉ lệ họ comment cf dưới mỗi bài viết (thề luôn kết quả chỉ ra còn sốc vcl, như tôi làm ví dụ)

### Hướng phát triển:
Để tăng độ khó cho game tạo job và deadline cho thằng Luộc Đỗ và anh em team ông thì có thể **tích hợp cả AI vào web nữa** =)))?


P/S: Mấy lần đi qua delta nhìn phòng SAP LAB thấy ông cháu ngồi code trong khi anh em đang học kì 1 thấy ngầu phết đó =))) keep it up fam 🔥. À mà how to apply cv vào đó vậy :v kiểu mở cừa vào ngồi khoe với ae trong đấy rồi nhận lại được ý kiến góp ý à :)))) hay là ngồi đợi chúng nó xem CV xong đ thèm rep :)))? Tôi cũng muốn đi thực tập FSoft lắm ý nma cứ ngựa ngựa, thích ngồi xàm lờ cuối lớp full slot với mấy lũ bạn cùng lớp SE hơn :v thay vì cắm đầu cắm cổ rush sản phẩm một mình một chỗ all-day :v. Đến anh Giang join street workout mà dạo này gặp nhìn bụng phệ vc :( Được cái điểm cộng tôi thấy ở ông mà tôi vẫn đang phải học tập theo là sự chuyên nghiệp trong việc chỉ đạo cả team project, rush deadline xong sớm và quả docs cho từng cái pet project ông làm nhìn chi tiết và dễ đến mức tôi tưởng package này của người khác ông folk về =))))

Chút tâm sự ngày mưa Dom D 08/09/2022...
From JS BCM Gen 10 with luv <3

Sincerely,
Tunna Duong

**Comment by thaiminhpv** [comment]
Cảm ơn góp ý tâm huyết của ông bạn nha 😁 Quá hợp lý 👏

**Comment by tunnaduong** [comment]
> Cảm ơn góp ý tâm huyết của ông bạn nha 😁 Quá hợp lý 👏

Nể lắm mới nói đấy =)))) chưa bao giờ viết issue cmn dài như này =)))

**Comment by tunnaduong** [comment]
Có gì anh em add tôi làm cùng dự án này cũng đc =)) kiểu tôi cũng thích học thêm tí AI :))) may có ông anh K15 AI phòng tôi mentor mẹ luôn
